@base=http://localhost:3000


### GET /users
GET {{base}}/users HTTP/1.1

### GET /users/:id
GET {{base}}/users/2 HTTP/1.1

### POST /users
POST {{base}}/users HTTP/1.1
content-type: application/json

{
  "name": "user1"
}

### PATCH /users
PATCH {{base}}/users/1 HTTP/1.1
content-type: application/json

{
  "name": "updated user"
}